### ISSUE TITLE
Examples should include idiomatic error handling 

### ISSUE THREAD

**Issue by peteyycz** [thedevsaddam/govalidator#29]
In your examples, the whole point was to show error validation errors, but in real-world applications, it's rarely the use case. As a GO API developer, I'm not sure how to handle empty validation error maps.

Please let me know if you think it's a good example and I could add them to a PR. :smile: 

```	
	err := v.ValidateJSON()
	if err.Get("_error") != "" {
		log.Print(err)
		http.Error(w, "Error happened processing the request", http.StatusInternalServerError)
		return

	}
	if len(err) != 0 {
		validationErr := map[string]interface{}{"validationError": err}
		json.NewEncoder(w).Encode(validationErr)
		return
	}

```

**Comment by sir-wiggles** [comment]
I think it would be nice if when calling `Validate*()` that it returns an actual error.  This would be a little more idiomatic I feel.

If I really want to get the actual `url.Values` then I can cast to an appropriate custom error type and get them.

Anyway, I want to say I really appreciate this library so much more than other validation libraries out there. So may thanks for this.

**Comment by RobvH** [comment]
There's a bit of a difference between the conventional way go unmarshalls JSON into a struct and PHP json_decodes. I was noticing a lot of my validation rules really don't matter (numeric, for example) b/c if passed a string, Go won't be able to unmarshall type string into an int32 so I always get that error back instead of the validation error saying it needs to be an integer (er, numeric).

You "can" dynamically parse JSON in Go. I'd like to test if that is a viable solution.
